name: deploy_ios

on:
  push:
    branches: [master]

jobs:
  deploy_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Bundle install
        run: cd ./ios && bundle install

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Inject google service account file
        run: |
          echo "${{ secrets.SPEECH_JSON }}" >> speech_acct.b64
          base64 -d -i speech_acct.b64 > ./assets/speech_acct.json

      - name: Install tools
        run: |
          flutter pub get
          cd ./ios && pod install

      - name: Flutter build release
        run: |
          flutter build ios --release --no-codesign

      - name: Deploy to TestFlight
        run: |
          cd ./ios && bundle exec fastlane beta
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}